version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: minimovie_db
    environment:
      MYSQL_ROOT_PASSWORD: Kira@8355
      MYSQL_DATABASE: mini_movie_db
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./backend
    container_name: minimovie_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: minimovie_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
